### ISSUE TITLE
Undocumented -output2 causes segfault

### ISSUE THREAD

**Issue by olddaos** [SkTim/OIWE#1]
Hi there!
Thanks for a great efforts, results are indeed very nice!

But one minor point : when I ran ./wordnvec exactly as described in docs, I got segfault. The reason is simple : in reality, it requires another file named -output2 in which it outputs negative part of embeddings. But this requirement is very hidden and typical user will just forgot to specify -output2.

The fix is very easy, though...

**Comment by luohongyin** [comment]
Hi, 

  Thank you. I will check it ASAP. The problem might be caused because once I tried to check the context vector but forgot to deal it after that. Thank you very much for reminding!
