### ISSUE TITLE
can u provide the dataset like RW and RG-65

### ISSUE THREAD

**Issue by sjm1992st** [SkTim/OIWE#2]
Hi, I want to test my method on the evaluation set,Can you provide your evaluation set and standard evaluation procedures?very thank u.

**Comment by luohongyin** [comment]
Hi,

The evaluation datasets are available at http://wordvectors.org/.

To calculate the spearman coefficient, I'm following the implementation of http://wordvectors.org/, which is available at https://github.com/mfaruqui/eval-word-vectors.

Hongyin

**Comment by sjm1992st** [comment]
Thank u very much
